server {
    # Escucha en el puerto 80 dentro del contenedor
    listen 80;

    # Directorio raíz
    root /usr/share/nginx/html;

    # Archivo de inicio
    index index.html index.htm;

    # Configuración principal para Flutter Routing
    # Esto es crucial para URLs como /perfil, que deben cargar index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
