name: CI Pipeline

on:
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Gradle (Java/Kotlin) ---
      - name: Set up JDK 21
        if: ${{ hashFiles('**/gradlew') != '' }}
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        if: ${{ hashFiles('**/gradlew') != '' }}
        run: |
          chmod +x ./gradlew
          ./gradlew build --stacktrace

      # --- Análisis estático con SonarCloud ---
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=sbenitezreyes_SACM
            -Dsonar.organization=sbenitezreyes-1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}